meilisearch:
  api_url: 'https://ms-411c470e0eac-11435.lon.meilisearch.io'
  api_key: 'c9622a7df0512f6f4cc3d34b9e7957277037171f'
  insert_size: 1000
  insert_interval: 10

source:
  type: postgres
  host: '34.132.68.121'
  port: 5432
  database: postgres
  user: postgres
  password: '_s]mk^]lvKz)XY^U'

progress:
  type: file  
  path: 'C:\\Python312\\Lib\\site-packages\\meilisync\\progress.json'

sync:
  - table: Post
    index: posts
    pk: id
    full: true
